language: go
sudo: required

# https://docs.travis-ci.com/user/languages/go/#go-import-path
go_import_path: github.com/etix/mirrorbits

go:
  - "1.10.x"
  - "1.11.x"
  - master

os:
  - linux

matrix:
  allow_failures:
    - go: master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgeoip-dev

install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env

script:
  - make
  - make test
